# Generated by Django 5.0.3 on 2024-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myuser123_groups_myuser123_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser123',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser123',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myuser123',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='myuser123',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='myuser123',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
