# Generated by Django 5.0.3 on 2024-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_myuser123_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('size', models.IntegerField(choices=[(1, '1'), (2, '2'), (4, '4'), (0, '4+')])),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('unreserved', 'Unreserved')], max_length=10)),
            ],
        ),
    ]
