# Generated by Django 5.0.3 on 2024-04-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=150)),
                ('food', models.CharField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
