# Generated by Django 5.0.3 on 2024-04-06 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='username',
        ),
    ]
