# Generated by Django 5.0.3 on 2024-04-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_dineinorder_dineinorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
