# Generated by Django 5.0.3 on 2024-04-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_dineinorderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
