# Generated by Django 5.0.3 on 2024-04-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_dineinorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinorder',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
