# Generated by Django 5.0.3 on 2024-04-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order123_delete_order11'),
    ]

    operations = [
        migrations.AddField(
            model_name='order123',
            name='user_name',
            field=models.CharField(default='none'),
        ),
    ]
