# Generated by Django 5.0.3 on 2024-04-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_order123_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order123',
            name='status',
            field=models.CharField(default='none'),
        ),
    ]
