# Generated by Django 5.0.3 on 2024-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_order123_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order123',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
