# Generated by Django 5.0.3 on 2024-05-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_order123_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order123',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
