# Generated by Django 5.0.3 on 2024-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_order123_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order69',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=6, null=True, unique=True)),
                ('total_price', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
