# Generated by Django 5.0.3 on 2024-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_order69'),
    ]

    operations = [
        migrations.AddField(
            model_name='order123',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
