# Generated by Django 5.0.3 on 2024-05-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_order123_paid_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order69',
        ),
    ]
