# Generated by Django 5.0.3 on 2024-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_delete_order69'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order123',
            name='order_number',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
